  spring:
        data:
          mongodb:
            uri=mongodb+srv://mapeandoQuilombos:Gabaritos1@mapeando:
              kcqiuu1:
                mongodb:
                  net/territory?retryWrites=true&w=majority: