spring:
  data:
    mongodb:
      host: ${MongoDB.MONGOHOST}
      port: ${MongoDB.MONGOPORT}
      username: ${MongoDB.MONGOUSER}
      password: ${MongoDB.MONGOPASSWORD}
      uri: ${MongoDB.MONGO_URL}
